---
- name: assert | Test if consul_template_consul_address is set correctly
  ansible.builtin.assert:
    that:
      - consul_template_consul_address is defined
      - consul_template_consul_address is string
    quiet: true
