---
# tasks file for nomad

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install consul-template
  ansible.builtin.package:
    name: consul-template
    state: present

- name: Create consul-template configuration directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "600"
  with_items:
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_config_dir }}/templates"

- name: Configure consul-template
  notify:
    - Restart consul-template
  block:
    - name: Copy consul-template service
      ansible.builtin.copy:
        src: "files/consul-template.service"
        dest: "/lib/systemd/system/consul-template.service"
        mode: "0750"

    - name: Remove legacy consul-template config
      ansible.builtin.file:
        path: "{{ consul_template_config_dir }}/config.hcl"
        state: absent

    - name: Copy consul-template config
      ansible.builtin.template:
        src: templates/consul.hcl.j2
        dest: "{{ consul_template_config_dir }}/consul.hcl"
        mode: "600"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start consul-template
  ansible.builtin.service:
    name: consul-template
    state: started
    enabled: true
